#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

#################### ~~~ ####################
# Install Homebrew
#################### ~~~ ####################
echo ""
if brew -v; then
	echo "✅ Homebrew already installed."
else
	echo "🚀 Installing Homebrew..."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

#################### ~~~ ####################
# Install OhMyZsh
#################### ~~~ ####################
echo ""
OhMyZsh=$HOME/.oh-my-zsh

if [[ -d $OhMyZsh ]]; then
	echo $OhMyZsh
	echo "✅ OhMyZsh already installed."
else
	echo "🚀 Installing OhMyZsh..."
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

#################### ~~~ ####################
# Link .zshrc file
#################### ~~~ ####################
echo ""
rm $HOME/.zshrc
ln -s $DOTFILES/zsh/.zshrc $HOME/.zshrc
echo "✅ Linked .zshrc file."
echo "🔥 Run \"source ~/.zshrc\""

#################### ~~~ ####################
# Install OhMyZsh SpaceShip Theme
#################### ~~~ ####################
echo ""
SpaceShipTheme=$HOME/.oh-my-zsh/custom/themes/spaceship-prompt

if [[ -d $SpaceShipTheme ]]; then
	echo $SpaceShipTheme
	echo "✅ SpaceShip theme already installed."
else
	echo "🚀 Run the following commands to install SpaceShipTheme"
	echo "git clone https://github.com/spaceship-prompt/spaceship-prompt.git \"\$ZSH_CUSTOM/themes/spaceship-prompt\" --depth=1"
	echo "ln -s \"\$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme\" \"\$ZSH_CUSTOM/themes/spaceship.zsh-theme\""
	echo "Change ZSH_THEME=\"spaceship\" in .zshrc file."
	echo "Finally run `source ~/.zshrc`"
fi

#################### ~~~ ####################
# Install PNPM
#################### ~~~ ####################
echo ""
echo "pnpm -v"
if pnpm -v; then
	echo "✅ PNPM already installed."
else
	curl -fsSL https://get.pnpm.io/install.sh | sh -
fi

#################### ~~~ ####################
# Install NODE
#################### ~~~ ####################
echo ""
echo "node -v"
if node -v; then
	echo "✅ NODEJS already installed."
else
	pnpm env use --global lts
fi

#################### ~~~ ####################
# Link Alacritty config
#################### ~~~ ####################
echo ""
rm -rf $HOME/.config/alacritty
ln -s $DOTFILES/alacritty $HOME/.config/alacritty
echo "✅ Linked Alacritty config."

#################### ~~~ ####################
# Link Neovim config
#################### ~~~ ####################
echo ""
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim
echo "✅ Linked Neovim config."
