#!/usr/bin/env bash

#################### ~~~ ####################
# Install Homebrew
#################### ~~~ ####################
if brew -v; then
	echo "✅ Homebrew already installed."
else
	echo "🚀 Installing Homebrew..."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

#################### ~~~ ####################
# Install OhMyZsh
#################### ~~~ ####################
OhMyZsh=$HOME/.oh-my-zsh

if [[ -d $OhMyZsh ]]; then
	echo "✅ OhMyZsh already installed."
else
	echo "🚀 Installing OhMyZsh..."
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

#################### ~~~ ####################
# Install OhMyZsh SpaceShip Theme
#################### ~~~ ####################
SpaceShipTheme=$HOME/.oh-my-zsh/custom/themes/spaceship-prompt

if [[ -d $SpaceShipTheme ]]; then
	echo "✅ SpaceShip theme already installed."
else
	echo "🚀 Installing SpaceShip Theme..."
	git clone https://github.com/spaceship-prompt/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1
	ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
fi
